# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StarterApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
	pod 'Google/SignIn'

  # Pods for StarterApp

  target 'StarterApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StarterAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'StarterApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StarterApp-tvOS

end
