# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeStarterApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
	pod 'Google/SignIn'

  # Pods for ReactNativeStarterApp

  target 'ReactNativeStarterApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactNativeStarterAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReactNativeStarterApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeStarterApp-tvOS

end
